#!/usr/bin/env node
// Smoke test for scripts/bump-version.mjs.
//
// Tests the exported `nextVersion` pure function for all bump kinds,
// suffix handling, and error cases.
//
// Usage: node scripts/__tests__/bump-version.smoke.mjs

import { nextVersion, setLockfileVersion } from "../bump-version.mjs";

function fail(msg) {
  console.error(`FAIL: ${msg}`);
  process.exit(1);
}

// patch bump
{
  const got = nextVersion("0.1.39", "patch");
  if (got !== "0.1.40") fail(`patch "0.1.39": expected "0.1.40", got "${got}"`);
  console.log("PASS: nextVersion(0.1.39, patch) === 0.1.40");
}

// minor bump
{
  const got = nextVersion("0.1.39", "minor");
  if (got !== "0.2.0") fail(`minor "0.1.39": expected "0.2.0", got "${got}"`);
  console.log("PASS: nextVersion(0.1.39, minor) === 0.2.0");
}

// major bump
{
  const got = nextVersion("0.1.39", "major");
  if (got !== "1.0.0") fail(`major "0.1.39": expected "1.0.0", got "${got}"`);
  console.log("PASS: nextVersion(0.1.39, major) === 1.0.0");
}

// minor resets patch
{
  const got = nextVersion("1.2.3", "minor");
  if (got !== "1.3.0") fail(`minor "1.2.3": expected "1.3.0", got "${got}"`);
  console.log("PASS: nextVersion(1.2.3, minor) === 1.3.0");
}

// major resets minor and patch
{
  const got = nextVersion("1.2.3", "major");
  if (got !== "2.0.0") fail(`major "1.2.3": expected "2.0.0", got "${got}"`);
  console.log("PASS: nextVersion(1.2.3, major) === 2.0.0");
}

// suffix is dropped
{
  const got = nextVersion("0.1.39-beta", "patch");
  if (got !== "0.1.40") fail(`patch "0.1.39-beta": expected "0.1.40", got "${got}"`);
  console.log("PASS: nextVersion(0.1.39-beta, patch) === 0.1.40 (suffix dropped)");
}

// basic patch still works (belt-and-suspenders)
{
  const got = nextVersion("1.0.0", "patch");
  if (got !== "1.0.1") fail(`patch "1.0.0": expected "1.0.1", got "${got}"`);
  console.log("PASS: nextVersion(1.0.0, patch) === 1.0.1");
}

// invalid kind throws
{
  let threw = false;
  try {
    nextVersion("1.0.0", "feat");
  } catch (e) {
    threw = true;
    if (!e.message.includes("Invalid bump kind")) {
      fail(`invalid kind: unexpected error message: "${e.message}"`);
    }
  }
  if (!threw) fail(`invalid kind "feat": expected a throw but got no error`);
  console.log("PASS: nextVersion(1.0.0, feat) throws Invalid bump kind");
}

// unparseable version throws
{
  let threw = false;
  try {
    nextVersion("not-a-version", "patch");
  } catch (e) {
    threw = true;
    if (!e.message.includes("Cannot parse version")) {
      fail(`bad version: unexpected error message: "${e.message}"`);
    }
  }
  if (!threw) fail(`bad version "not-a-version": expected a throw but got no error`);
  console.log("PASS: nextVersion(not-a-version, patch) throws Cannot parse version");
}

// --- setLockfileVersion ---------------------------------------------------

const SAMPLE_LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "argus"
version = "0.1.38"
dependencies = [
 "tauri",
]

[[package]]
name = "zerocopy"
version = "0.7.0"
`;

// updates only the argus block, leaves other packages untouched
{
  const got = setLockfileVersion(SAMPLE_LOCK, "argus", "0.2.0");
  if (!got.includes('name = "argus"\nversion = "0.2.0"')) {
    fail(`setLockfileVersion: argus version not updated:\n${got}`);
  }
  if (!got.includes('name = "anyhow"\nversion = "1.0.0"')) {
    fail(`setLockfileVersion: anyhow version should be untouched`);
  }
  if (!got.includes('name = "zerocopy"\nversion = "0.7.0"')) {
    fail(`setLockfileVersion: zerocopy version should be untouched`);
  }
  console.log("PASS: setLockfileVersion updates only the argus entry");
}

// throws when the package is absent (fail loudly, never silently drift)
{
  let threw = false;
  try {
    setLockfileVersion(SAMPLE_LOCK, "nonexistent", "9.9.9");
  } catch (e) {
    threw = true;
    if (!e.message.includes("Could not find")) {
      fail(`missing pkg: unexpected error message: "${e.message}"`);
    }
  }
  if (!threw) fail(`missing pkg: expected a throw but got no error`);
  console.log("PASS: setLockfileVersion(missing pkg) throws");
}

console.log("All bump-version cases passed.");
